version: '3.7'

services:
  api:
    image: main_service
    container_name: main_service
    restart: always
    volumes:
      - ./:/code
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - searchnet
    entrypoint: "./main-entrypoint.sh"

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    restart: always
    ports:
      - "9114:9114"
    command:
      - '--es.uri=http://elasticsearch:9200'
    networks:
      - searchnet

  redis:
    image: redis:alpine
    restart: always
    command: redis-server
    volumes:
      - movie_search_redis_data:/data
    ports:
      - "6379:6379"
    container_name: redis
    networks:
      - searchnet

networks:
  searchnet:
    external: true

volumes:
  movie_search_redis_data: