version: '3.7'


services:
  api:
    build: .
    container_name: search_movie
    environment:
      - REDIS_HOST=dockernet
    volumes:
      - ./:/code
    networks:
      - dockernet
    expose:
      - 8000
    ports:
      - "8000:8000"
    entrypoint: "./main-entrypoint.sh"

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - movie_search_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - dockernet
    command: redis-server

  elasticsearch:
    image: elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - dockernet
    ports:
      - "9200:9200"

  kibana:
    image: kibana:8.2.2
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - dockernet

networks:
  dockernet:
    external: true

volumes:
  es_data:
    driver: local
  movie_search_redis_data:
