apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: localhost:5000/search-movie-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-server-config
          command: [ "/bin/bash" ]
          args: [ "-c", "python manage.py runserver 0.0.0.0:8000" ]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-server-config
data:
  ELASTIC_SEARCH_HOSTS: "['http://10.108.237.44:9200']"
  ELASTIC_SEARCH_INDEX_NAME: "movies"
  REDIS_HOST: "10.101.245.215"
  REDIS_PORT: "6379"

---
apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
