apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-deployment
  labels:
    app: elastic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      name: elastic
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic
          image: elasticsearch:8.12.2
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
          ports:
            - containerPort: 9200

---

apiVersion: v1
kind: Service
metadata:
  name: elastic
spec:
  type: NodePort
  selector:
    app: elastic
  ports:
    - port: 9200
      targetPort: 9200
