apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: elasticsearch:8.12.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
          envFrom:
            - configMapRef:
                name: elasticsearch-config
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
      volumes:
        - name: es-data-volume
          emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
data:
  node.name: "es01"
  cluster.name: "es-docker-cluster"
  discovery.type: "single-node"
  bootstrap.memory_lock: "true"
  xpack.security.enabled: "false"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: ClusterIP
